columnSuffix: enxyxgne
contentColumnType: string
fieldGroup: 358ccbfe-1443-4d13-bee7-7b4a04571850 # fixture
handle: homeOrAway
instructions: ''
name: 'home Or Away'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - home
        -
          - value
          - home
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - away
        -
          - value
          - away
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
