defaultPlacement: end
enableVersioning: true
handle: league
name: League
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  90d3f773-6c0f-4846-8174-c9c2a3d5ff2d: # football
    enabledByDefault: true
    hasUrls: true
    template: league/_entry
    uriFormat: 'league/{slug}'
type: channel
