defaultPlacement: end
enableVersioning: true
handle: teams
name: Teams
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  90d3f773-6c0f-4846-8174-c9c2a3d5ff2d: # football
    enabledByDefault: true
    hasUrls: true
    template: teams/_entry
    uriFormat: 'teams/{slug}'
type: channel
